apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugonnawinms-slash-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ugonnawinms-slash-test
  template:
    metadata:
      labels:
        app: ugonnawinms-slash-test
    spec:
      containers:
      - name: ugonnawinms-slash-test
        image: oze4/ugonnawinms-slash-test:latest
        env:
        - name: PORT
          value: ${PORT}
        ports:
        - containerPort: ${PORT}